# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calculate_log_probability_cpp <- function(kmer_genus_count, word_specific_priors, genus_counts) {
    .Call(`_phylotypr_calculate_log_probability_cpp`, kmer_genus_count, word_specific_priors, genus_counts)
}

calculate_log_probability_cpp2 <- function(kmer_genus_count, word_specific_priors, genus_counts) {
    .Call(`_phylotypr_calculate_log_probability_cpp2`, kmer_genus_count, word_specific_priors, genus_counts)
}

calculate_log_probability_cpp3 <- function(kmer_genus_count, word_specific_priors, genus_counts) {
    .Call(`_phylotypr_calculate_log_probability_cpp3`, kmer_genus_count, word_specific_priors, genus_counts)
}

